# Generated by Django 4.2.2 on 2023-06-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discount')),
                ('room_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roomrate')),
            ],
        ),
    ]
